"""Generate FINDINGS.json for the ManschouRey audit (baseline fe97cc1).

Each finding merges duplicate root causes across reviewers; `sources` lists the proposing reviewer IDs.
Severity and independent_review reflect the A15 reconciliation (agents/A15-challenge-and-reconciliation.md).
Run: python3 build-findings.py > ../../FINDINGS.json
"""
import json

BASE = "fe97cc1ba1400f5c118d7c290bc1000574ac6dd0"

def F(id, title, domain, severity, confidence, status, locations, observed, expected, reproduction, evidence,
      impact, scope, fix, acceptance, effort, sources, review="pending", artifact="repository source at baseline"):
    return {
        "id": id, "title": title, "domain_owner": domain, "severity": severity, "confidence": confidence,
        "status": status, "affected_artifact": artifact, "baseline_commit": BASE, "locations": locations,
        "observed": observed, "expected": expected, "reproduction": reproduction, "evidence": evidence,
        "impact": impact, "scope": scope, "recommended_fix": fix, "acceptance_test": acceptance,
        "dependencies_effort_uncertainty": effort, "proposed_by": sources, "independent_review": review,
    }

FINDINGS = [
F("MSR-CULT-001",
  "60 of 72 records carry template/placeholder 'heritage evidence' (water CAS, Matrix-#HEX formulas, generic manuscript, grid coordinates, generic UNESCO label) presented as authentic in UI and exports",
  "Cultural data / A03+A04", "High", "high: exact string counts reproduced by A00 and W1",
  "reproduced",
  ["packages/core/src/tokens/heritage-data.ts:558 (first of 120 casNumber '7732-18-5 (Authentic Historical Specimen)')",
   "heritage-data.ts geoSpatial.coordinates: six points lat 32.4279+0.5i / lng 53.688+0.3i reused by 60 colors",
   "heritage-data.ts historicalManuscriptRef: 'رسالات کهن رنگرزی سنتی و صنعتی ایران زمین' x60",
   "heritage-data.ts chemicalFormula 'Natural Organic / Mineral Complex (Matrix #HEX)' x54",
   "packages/core/src/tokens/palettes.ts:38-40 (selection prefers the grid point)",
   "app/template.html:1113 'نام کانی‌شناسی اصیل', :1139 'رساله کهن خطی و سند تاریخی مرجع', :1366 static 'موزه هنرهای اسلامی' badge",
   "packages/core/tokens/w3c-tokens.json and style-dictionary.json (120 occurrences each of the water CAS)"],
  "CAS 7732-18-5 is water (H2O). The 'formula' fields embed the color's own HEX value. Coordinates are an arithmetic grid (e.g. 54.288000000000004). The UI labels these fields 'authentic' and 'reference historical manuscript', and a static museum badge appears on every color.",
  "Heritage fields either cite a locatable source for the specific claim, or are empty and labeled 'no source recorded'. Placeholders must never be labeled authentic or exported as data (audit brief §4C/§4D; do not fabricate).",
  "grep -c '7732-18-5 (Authentic Historical Specimen)' packages/core/src/tokens/heritage-data.ts -> 120; grep -c 7732-18-5 packages/core/tokens/w3c-tokens.json -> 120; grep -o '\"lat\": [0-9.]*' heritage-data.ts | sort | uniq -c (six values x10); open the evidence dialog for any color to see the labels.",
  ["DATA_QUALITY.md §2", "agents/W1-cultural-review.md MSR-DATA-001/002/003, CULT-004, CULT-006", "evidence/W1-cultural/analyze-data.out.json", "evidence/W2-browser/screens/wf-evidence-en-light.jpg"],
  "Cultural: presents machine-generated values as documentary evidence about Iranian heritage. Distribution: token consumers receive 'Authentic Historical Specimen' data. Mitigation: provenance.heritageStatus='unverified' is set for every record, and README.fa/DESIGN_SYSTEM disclaim authentication.",
  "60/72 colors in 10/12 palettes (all except isfahan-tiles; achaemenid-majesty has the water CAS but specific other fields).",
  "Replace the placeholder values with null plus status 'no-source' in the data. Remove the 'اصیل' and 'سند تاریخی مرجع' labels and the static museum badge. Show 'no source recorded' in the UI. Keep the stable IDs.",
  "grep for 7732-18-5, 'Matrix #', the generic manuscript phrase and the six grid latitudes returns 0 in src, tokens and HTML. Every displayed heritage field either has a source ID or shows 'no source recorded'.",
  "0.5-1.5 days engineering; no research needed to remove. Re-populating the fields needs archive/museum research (backlog).",
  ["W1", "A00", "W2"]),
F("MSR-I18N-001",
  "English UI inverts or upgrades the hedged Persian provenance wording ('Primary source documented', 'Authentic Iranian Heritage Colors', 'documented historical sources', 'Spectral Physics')",
  "i18n / A05+A06", "High", "high: verbatim string comparison; data says not-verified for 72/72",
  "reproduced",
  ["app/enhancements.js:8 (EN) vs :11 (FA)", "app/app.js:77-79 (EN hero) vs :38-40 (FA)", "code_artifact.html and code_artifact_en.html (built copies)"],
  "EN: 'Historical & Mineral: Primary source documented.' FA: 'اطلاعات تاریخی و ماده: نیازمند بررسی منبع.' EN hero: 'documented historical sources'; FA: 'وضعیت روشن منابع تاریخی'.",
  "Bilingual semantic parity. The caveat must not change meaning across languages (audit brief §4E). The data model has heritageStatus='unverified' and verification='not-verified' for all 72 records (palettes.ts:49,58).",
  "Open code_artifact_en.html, choose any palette, open the evidence dialog: the banner reads 'Primary source documented'.",
  ["agents/A00-lead-sequential-passes.md (A06 addendum)", "agents/W1-persian-language.md MSR-I18N-001/002", "agents/W2-browser-a11y-ux.md MSR-UX-001", "evidence/W2-browser/screens/wf-evidence-en-light.jpg"],
  "English-reading users, reviewers and funders are told that the heritage annotations are documented from primary sources when the project's own data says they are not.",
  "All 72 colors in the English edition and the fa edition after switching to English.",
  "Replace the English strings with faithful translations (see EDITORIAL_REWRITE_SAMPLES.md §3). Generate the banner from each record's provenance fields, not from a constant string.",
  "An automated test asserts that the EN and FA banner text is derived from provenance status, and that no EN string contains 'documented', 'authentic' or 'physics' unless the record status supports it.",
  "2-4 hours.", ["A00", "W1", "W2"]),
F("MSR-A11Y-001",
  "Light theme renders sample text at 1.02-1.78:1 while the adjacent badge reports '16.2:1 (AAA)'",
  "Accessibility / A08", "High", "high: measured by axe, computed styles and screenshots",
  "reproduced",
  ["app/polish.css:55-57", "app/polish.css:98-101", "app/app.js:2204-2217, 2523-2527 (inline sample colors)", "app/app.js:2045-2046, 2499-2500 (badge computed from the palette pair)", "app/app.js:19 (auto light theme)"],
  "Isfahan card body text renders rgb(51,65,85) on rgb(11,19,43) = 1.78:1; the 3D drawer heading renders 1.02:1; both badges say 16.2:1 (AAA).",
  "WCAG 2.2 SC 1.4.3 Contrast (Minimum) 4.5:1. A contrast indicator must describe the rendered colors.",
  "evidence/W2-browser/scripts/06-perf-graphics.mjs -> lightTargets; scripts/04-axe.mjs (light theme).",
  ["evidence/W2-browser/results/06-perf-graphics.json", "evidence/W2-browser/screens/light-card-isfahan-zoom.jpg", "evidence/W2-browser/screens/light-drawer-heading.jpg"],
  "Text is unreadable for everyone in light theme, and the tool's central promise (contrast-checked samples) is visibly false. Light-OS users get this theme by default.",
  "All 12 palette cards and the 3D studio mockup in light theme, both editions.",
  "Scope the light-theme !important overrides away from preview surfaces, and compute the badge from getComputedStyle.",
  "In light theme, axe reports 0 color-contrast violations on [id^=card-body-] and #mockupCard h4, and the badge ratio matches the computed ratio within ±0.05.",
  "0.5-1 day.", ["W2"]),
F("MSR-A11Y-002",
  "At 400% zoom (320x256 CSS px) the sticky header covers the viewport; 0 px of content is visible (fa)",
  "Accessibility / A08", "Medium", "high for the measurement; medium for real Ctrl+ zoom (emulated by viewport)",
  "reproduced",
  ["app/template.html:200 (header sticky top-0) wrapping 13 controls at :204-318"],
  "Header height is 277 px at 320x256 (fa) and 233 px (en), leaving 0 px and 23 px of content.",
  "SC 1.4.10 Reflow; SC 2.4.11 Focus Not Obscured (Minimum).",
  "evidence/W2-browser/scripts/08-zoom400.mjs",
  ["evidence/W2-browser/results/08-zoom400.json", "evidence/W2-browser/screens/zoom400-320x256-fa-scrolled.jpg"],
  "Low-vision users who zoom to 400% cannot use the page.",
  "Every page view at high zoom or on a short viewport.",
  "Make the header non-sticky below a height breakpoint, or collapse secondary controls into a menu.",
  "At 320x256 the header takes at most 25% of the viewport, and focus is never hidden under it.",
  "0.5 day.", ["W2"]),
F("MSR-LIC-001",
  "@persian-palette/core declares license 'MIT' while bundling or loading non-MIT code (apca-w3 Limited W3 License, MCU Apache-2.0; colorparsley AGPL-3.0 loaded at runtime by ESM)",
  "Licensing / A12", "High", "high on the facts; legal consequence needs counsel",
  "reproduced",
  ["packages/core/package.json 'license'", "packages/core/dist/index.cjs (apca-w3 and MCU bundled)", "packages/core/dist/math/apca.js:2 (ESM import chain to colorparsley)"],
  "package.json says 'MIT'. The CJS bundle contains apca-w3 and MCU code. ESM consumers install and evaluate colorparsley (AGPL-3.0), although its functions are never called.",
  "The license metadata must describe what is distributed. APCA-W3 terms restrict scope (web content only) and prohibit commercial use without a signed agreement.",
  "grep '// node_modules/' packages/core/dist/index.cjs; npm view apca-w3 license; W3's resolve-hook trace.",
  ["agents/W3-security-licenses-interop-release.md §5, MSR-LIC-001", "evidence/W3-security/colorparsley-reachability.log"],
  "License scanners and SBOMs see 'MIT only'. Downstream commercial or native use may conflict with the APCA-W3 terms.",
  "Every consumer of the npm tarball; the HTML studio also bundles apca-w3.",
  "Get counsel. Set a truthful SPDX expression or externalize apca-w3 from the CJS build, document the APCA terms, and consider an optional peer dependency.",
  "The tarball's license metadata and README state all bundled and runtime terms; a license scanner run in a consumer lists apca-w3 and colorparsley with their real licenses.",
  "0.5-3 days plus counsel time.", ["W3"]),
F("MSR-CULT-002",
  "24 of 72 HEX values equal modern named-color list entries (including all 7 'Persian X' names), yet the data calls several of them 'world standard', 'registered' or accurately calibrated heritage colors",
  "Cultural data / A03", "Medium", "high for the exact matches; medium for intent",
  "source-confirmed",
  ["heritage-data.ts meaningFa: isfahan-tiles-c1 (:30), -c2 (:114), -c3 (:198); achaemenid-majesty-c1 (:549); behzad-miniature-c4 (:1320); persian-gulf-pearls-c1 (:3144); gardens-of-shiraz-c1 (:3663)"],
  "Examples: #1C39BB 'Persian Blue', #CC3333 'Persian Red', #00A693 'Persian Green', CSS #40E0D0 turquoise, #DAA520 goldenrod. Data text: 'استاندارد جهانی فیروزه‌ای ایرانی', 'اصلاح شده برای بازتاب دقیق کبالت ...'. One record admits 'معروف به Persian Green در کاتالوگ‌های جهانی'.",
  "A modern list value may be used as a design choice, but it should not be presented as a heritage standard or as a measured match (audit brief §4C: separate the documented name from the exact digital match).",
  "Compare every HEX with the W3C CSS Color 4 named colors and the Wikipedia-derived color list (W1 sources S001 and S002).",
  ["evidence/W1-cultural/ref/named-color-matches.json", "SOURCES.md S001, S002", "agents/W1-cultural-review.md MSR-CULT-001"],
  "Designers may believe they are using historically calibrated values.",
  "24 colors; 7 of them carry 'Persian' names from modern lists.",
  "Label each HEX as 'designer choice' and name its list origin where it has one ('matches CSS named color turquoise'). Remove 'world standard', 'accurate' and 'calibrated'.",
  "No meaningFa or meaning string contains 'استاندارد جهانی', 'دقیق' or 'ثبت‌شده' for a designer-choice HEX; the ledger's design_status is shown in the UI.",
  "2-4 hours of copy plus a data field.", ["W1", "A00"]),
F("MSR-DATA-001",
  "Wrong or mismatched chemical identifiers in the 12 specific records (invalid CAS check digit, CoO CAS for Co3O4, neutral-acetate CAS for basic acetate, molar-mass error)",
  "Data / A04", "Medium", "high: check-digit arithmetic and library lookup; PubChem itself was blocked",
  "source-confirmed",
  ["heritage-data.ts:1329/:1371 (behzad-miniature-c4, 1260-15-5)", ":459/:501 (isfahan-tiles-c6, 1307-96-6)", ":207/:249 (isfahan-tiles-c3, 142-71-2)"],
  "1260-15-5 fails the CAS check digit (carminic acid is 1260-17-9); 1307-96-6 is CoO while the formula is Co3O4; 142-71-2 is neutral copper(II) acetate; the verdigris molar mass is 370.2 vs 376.76 computed.",
  "Chemical identifiers must correspond to the stated substance.",
  "python3 evidence/W1-cultural/cas_probe.py; evidence/W1-cultural/molar-mass-check.py",
  ["evidence/W1-cultural/ref/cas-lookup.tsv", "evidence/W1-cultural/molar-mass-check.out.tsv"],
  "Exported chemistry is wrong for users who rely on it.", "4 records.",
  "Correct or remove the identifiers, and add a CAS check-digit validator to the schema test.",
  "The schema test rejects invalid CAS check digits; the ledger rows for these fields become supported or removed.",
  "1-2 hours.", ["W1"]),
F("MSR-CULT-003",
  "Records contradict themselves (basalt as CaCO3 or bronze; shells vs indigo; manganese extraction vs cobalt formula; Hormuz coordinates under a Persepolis reference)",
  "Cultural data / A03", "Medium", "high: internal contradictions quoted verbatim",
  "source-confirmed",
  ["heritage-data.ts achaemenid-majesty-c1 (:552,:561), -c3 (:716), -c4 (:804), -c5 (:888), -c6 (:964 vs :972)", "isfahan-tiles-c6 (:457)", "toranj-illumination-c5", "hyrcanian-forests"],
  "e.g. achaemenid-majesty-c1 coordinates 27.0628, 56.4589 (Hormuz Island), 472.8 km from the WHC 114 Persepolis reference it cites; this is not detected as a conflict because both coordinate copies agree.",
  "A record's fields must be mutually consistent before any source work.",
  "CULTURAL_CLAIMS.csv rows with evidence_status=contradicted; A00 re-ran the Hormuz record through the built package.",
  ["CULTURAL_CLAIMS.csv", "agents/W1-cultural-review.md MSR-CULT-002", "agents/W1-data-quality-draft.md §2"],
  "Undermines trust in every field of the record.", "At least 8 records.",
  "Fix or blank the contradictory fields; add a consistency review to the contribution checklist.",
  "Zero 'contradicted' ledger rows of the internal-contradiction type remain.",
  "0.5 day.", ["W1"]),
F("MSR-CULT-004",
  "Palettes flatten chronology, region and community (Timurid/Safavid, Ilkhanid/Safavid, Qashqai/Bakhtiari, Yazd/Lut/Qaenat, Gulf/Makran)",
  "Cultural representation / A03", "Medium", "medium: background art-historical knowledge; primary pages blocked; needs expert review",
  "suspected",
  ["heritage-data.ts behzad-miniature (-c4 artMovement 'مکتب اصفهان صفوی ...', -c6 Samarkand)", "isfahan-tiles-c5 historicalContextFa (Öljaitü mihrab)", "nomadic-rugs palette"],
  "A Behzad (Timurid/early-Safavid Herat) palette includes Reza Abbasi (later Isfahan school) attributions; one rug palette merges two distinct nomadic confederations.",
  "Preserve regional, linguistic and chronological distinctions (audit brief §4C).",
  "Qualitative review in agents/W1-cultural-review.md.",
  ["agents/W1-cultural-review.md MSR-CULT-003"],
  "Presents Persian culture as more uniform than it is.", "Several palettes.",
  "Add per-palette period and region fields and split or rename palettes where needed, after review by a subject specialist.",
  "A subject-specialist review is recorded; palette descriptions state period and region explicitly.",
  "Research: days to weeks; needs a human specialist.", ["W1"]),
F("MSR-CULT-005",
  "historicalManuscriptRef is uncitable for 60 records and unlocatable or unverified for the other 12",
  "Cultural data / A03+A04", "Medium", "high for the 60 generic references; medium for the 12 (sources blocked)",
  "evidence-gap",
  ["heritage-data.ts mineralogical.historicalManuscriptRef (72)", "app/app.js:339 renders it under 'رساله کهن خطی و سند تاریخی مرجع'"],
  "The 12 specific references (e.g. Abu'l-Qasim Kashani's 'Arayis al-Jawahir', Qazi Ahmad Qumi's 'Golestan-e Honar', inscription DSf) name real works, but with no edition, page or passage; none was read in this audit.",
  "A citation must identify the edition and locator and support the specific claim.",
  "SOURCES.md research backlog.", ["SOURCES.md", "agents/W1-cultural-review.md MSR-CULT-004"],
  "Readers cannot verify the claims.", "72 records.",
  "Convert the references to structured citations (work, edition, locator, claim supported) or mark them 'reference to be located'.",
  "Every displayed reference has a locator, or is labeled as not yet located.",
  "Research: weeks; needs library or archive access.", ["W1"]),
F("MSR-SCI-001",
  "Physically impossible dominant wavelengths are exported under a 'physics' key for black and for two purple-sector colors",
  "Color science / A02", "Medium", "high: chromaticity test against D65 and the purple line",
  "reproduced",
  ["toranj-illumination-c6 #000000 (610 nm)", "gardens-of-shiraz-c1 #FE28A2 (652 nm)", "gardens-of-shiraz-c2 #8B1E3F (631 nm)", "packages/core/src/tokens/palettes.ts:41-43 (physics block)", "packages/core/src/math/spectral.ts:1-4 ('Models physical reflectance curves')"],
  "Black has no chromaticity; purple-sector colors have only a complementary wavelength. The spectral module doc comment claims physical modeling, contradicting DESIGN_SYSTEM.md ('Gaussian illustrations').",
  "Physical quantities must be physically possible and labeled as illustrative when they are not measured.",
  "node evidence/A02-color/oracle-comparison.mjs <dist> <oracle-dir> -> dominantWavelength section.",
  ["evidence/A02-color/oracle-comparison.out.json", "evidence/A13-qa/diagnostic.test.mjs"],
  "Presents invented physics as data; damages scientific credibility.", "3 records; the doc comment affects all users of the API.",
  "Remove dominantWavelengthNm where undefined; rename 'physics' to 'illustrative' in exports; rewrite the spectral.ts comment (EDITORIAL_REWRITE_SAMPLES.md §4).",
  "The diagnostic DEFECT test for dominant wavelength passes; the exported extension has no 'physics' key without a caveat.",
  "2-4 hours.", ["A00"]),
F("MSR-SCI-002",
  "Digital Oklab interpolation is presented as mixing historical pigments in the UI and public API names",
  "Color science / A02", "Medium", "high",
  "reproduced",
  ["app quick mixer (no caveat shown)", "packages/core/src/math/color-mixing.ts (mixHistoricalPigments, MixedPigmentResult, generatePigmentGradient)"],
  "The quick mixer shows no caveat; the API keeps 'pigment' names although its doc comments say 'not physical pigment mixing'.",
  "Label digital interpolation as such at the point of use (audit brief §4B).",
  "evidence/W2-browser/results/02-workflows.json quick-mixer.caveatText:false.",
  ["agents/W2-browser-a11y-ux.md MSR-UX-005", "agents/A00-lead-sequential-passes.md A02"],
  "Users may infer subtractive paint behavior.", "Mixer UI and 3 API names.",
  "Add a caveat line to the mixer; deprecate the 'pigment' names in favor of mixColors/generateGradient in the next major version.",
  "The mixer shows a caveat; the deprecated names emit a JSDoc @deprecated.",
  "1-2 hours.", ["W2", "A00"]),
F("MSR-SCI-003",
  "Oklab interpolation clips out-of-gamut results per channel without documentation",
  "Color science / A02", "Low", "high", "reproduced",
  ["packages/core/src/math/oklab.ts:46-49 (linearToSrgb clamp)"],
  "103 of 7,665 palette-pair interpolants fall outside sRGB; clipping adds up to ΔEOK 0.0138.",
  "Document the gamut behavior, or use CSS Color 4 gamut mapping.",
  "evidence/A02-color/oracle-comparison.out.json mixing section.", ["evidence/A02-color/"],
  "Small hue/chroma errors below a typical JND.", "About 1.3% of palette mixes.",
  "Document it; optionally apply chroma-reduction gamut mapping.", "The docs state the clipping behavior.", "1 hour.", ["A00"]),
F("MSR-I18N-002",
  "English edition and language toggle leave Persian content, a Persian <title>, and no lang attributes on mixed-language text; English-named data fields contain Persian",
  "i18n + Accessibility / A05+A08", "Medium", "high", "reproduced",
  ["code_artifact_en.html:6 (<title>)", "scripts/build-app.mjs (string-replace EN build)", "app/template.html:967, 1178, 1356 (no data-i18n)", "heritage-data.ts description/culturalContext/unescoRef/role/meaning/artMovement contain Persian (12/12, 72/72)", "app/app.js:12 (stored fa preference overrides the EN file)"],
  "11-41 Persian text nodes per dialog in English mode; 0 lang attributes on 25 Latin phrases in fa; roleEn = 'Primary Accent' for all 72.",
  "SC 3.1.2 Language of Parts; SC 2.4.2 Page Titled; bilingual feature parity.",
  "evidence/W2-browser/scripts/03-denied-and-en.mjs, 05-keyboard-a11y.mjs.",
  ["agents/W2-browser-a11y-ux.md MSR-I18N-001, MSR-A11Y-009", "agents/W1-persian-language.md MSR-I18N-003"],
  "English-only users and screen readers get garbled or untranslated content.", "Both editions.",
  "Add real English data fields, data-i18n on the static caveats, lang/dir on mixed spans, and a per-edition <title>; do not let a stored preference override the EN file.",
  "In English mode, no text node outside lang=fa spans contains Arabic-script characters; the <title> matches the edition language.",
  "1-3 days, including translation.", ["W1", "W2", "A00"]),
F("MSR-I18N-003",
  "normalizeColorName misses common Persian/Arabic variants (ۀ, ى, أ/إ, ئ, ة) and all digit forms",
  "i18n / A05", "Medium", "high: runnable 24-case probe", "reproduced",
  ["packages/core/src/engine.ts:8-11"],
  "12 of 24 probe cases fail; getColor('nomadic-rugs','کرم خامۀ پشمی') throws; 'لاجوردى' (alef maksura) fails.",
  "Search keys fold standard Persian/Arabic variants and digits while display text stays unchanged.",
  "node evidence/W1-cultural/normalization-probe.mjs; evidence/A13-qa/diagnostic.test.mjs.",
  ["evidence/W1-cultural/normalization-probe.out.txt"], "Valid Persian queries fail.", "Library and studio search.",
  "Add explicit folding: ى→ی, ۀ→ه, أ/إ/آ→ا, ئ→ی, ة→ه, and Persian/Arabic-Indic digits → ASCII.", "All 24 probe cases pass.", "1-2 hours.", ["W1", "A00"]),
F("MSR-I18N-004",
  "Unsupported superlatives in Persian data and UI ('اصیل', 'استاندارد جهانی', 'ثبت‌شده جهانی', 'کد رسمی', 'دقیق', '۱۰۰٪')",
  "Editorial / A05+A06", "Medium", "high: verbatim", "source-confirmed",
  ["heritage-data.ts (e.g. :108, :114, :543, :1051, :1067)", "app/template.html:649, 1113, 1139, 1523"],
  "'فیروزه‌ای اصیل', 'استاندارد جهانی فیروزه‌ای ایرانی', 'رنگدانه اصیل شنگرف'.",
  "Unsupported authenticity claims must be removed or qualified (audit brief §4E).",
  "agents/W1-persian-language.md §4 lists every occurrence with its line.",
  ["agents/W1-persian-language.md MSR-I18N-005"], "Overstates the evidence to Persian readers.", "Dozens of strings.",
  "Remove the adjectives or qualify them ('الهام‌گرفته از'); keep stable IDs.", "A grep for the listed terms in data and UI returns only qualified uses.", "0.5 day.", ["W1"]),
F("MSR-I18N-005", "English color names change the meaning of the Persian names; transliteration is inconsistent (Tacara/Tachara)",
  "i18n / A05", "Low", "medium: translation judgment; native review recommended", "source-confirmed",
  ["heritage-data.ts nameEn of nomadic-rugs-c2, -c4; yazd-saffron-desert-c2, -c5; achaemenid-majesty-c5, -c6; :964 vs :897"],
  "e.g. 'Tacara' (nameEn) vs 'Tachara' (originSite).", "Consistent transliteration and faithful names.", "agents/W1-persian-language.md MSR-I18N-006.",
  ["agents/W1-persian-language.md"], "Minor confusion.", "About 9 names.", "Adopt one transliteration scheme; review the names.", "A style-guide check passes.", "2 hours.", ["W1"]),
F("MSR-I18N-006", "Bidi mangling of hex codes and Latin-in-parentheses names in RTL", "i18n / A05+A08", "Low", "high (visual)", "reproduced",
  ["app/app.js color-name and hex renderers (see W2 MSR-A11Y-011)"], "Rendered '120A8F#' and '(120A8F#'.", "SC 1.3.2; wrap codes in <bdi dir=ltr>.",
  "evidence/W2-browser/screens/light-drawer-heading.jpg", ["agents/W2-browser-a11y-ux.md MSR-A11Y-011"], "Codes are misread.", "Many labels.",
  "Wrap hex values and Latin names in <bdi> or dir=ltr spans.", "The screenshots show '#120A8F' in RTL.", "1-2 hours.", ["W2"]),
F("MSR-A11Y-003", "Light theme leaves pale '-300' accent text on white (1.2-1.6:1); axe counts 295 contrast failures across states",
  "Accessibility / A08", "Medium", "high", "reproduced", ["app/polish.css light-theme rules; Tailwind -300 text classes in template.html"],
  "295 color-contrast node-instances.", "SC 1.4.3.", "evidence/W2-browser/scripts/04-axe.mjs", ["evidence/W2-browser/results/04-axe-summary.json"],
  "Hard to read in light theme.", "Global chrome in light theme.", "Define light-theme text tokens with at least 4.5:1 contrast.", "axe color-contrast = 0 in light theme outside decorative elements.", "0.5-1 day.", ["W2"]),
F("MSR-A11Y-004", "72 nested interactive controls, and 72 evidence buttons below the 24 px target size", "Accessibility / A08", "Medium", "high", "reproduced",
  ["app/app.js:2248-2266"], "Buttons inside role=button; targets 14x36 px.", "SC 4.1.2; SC 2.5.8.", "axe nested-interactive and target-size.",
  ["evidence/W2-browser/results/04-axe-summary.json", "results/05-keyboard-a11y.json"], "Confusing for screen readers; hard to hit on touch.", "All 72 color items.",
  "Flatten the structure (one control per item plus a separate evidence button of at least 24x24).", "axe reports 0 for both rules.", "0.5 day.", ["W2"]),
F("MSR-A11Y-005", "Wrong or generic accessible names; theme and language toggles fail label-in-name; the EN language button announces the wrong action",
  "Accessibility / A08", "Medium", "high", "reproduced", ["app/enhancements.js:86, 96 (auto-naming)", "theme/language toggles in app/template.html header"],
  "The 3D drawer close button is named 'select color'; 5 selects are named 'adjust color'; in EN the language button says 'switch to English'.",
  "SC 4.1.2; SC 2.5.3 Label in Name; SC 2.4.6.", "evidence/W2-browser/scripts/05-keyboard-a11y.mjs", ["evidence/W2-browser/results/05-keyboard-a11y.json"],
  "Screen-reader users hear wrong actions.", "About 10 controls.", "Name controls explicitly; stop auto-naming by position.", "names_* checks show no mismatches.", "2-4 hours.", ["W2"]),
F("MSR-A11Y-006", "Toggle/tab states not exposed, status changes not announced, export code block not keyboard-focusable",
  "Accessibility / A08", "Low", "high", "reproduced", ["app/template.html:686 (pre#exportCodeBlock)", "toggle buttons and tab widgets in dialogs", "empty-search and camera-error states"],
  "No aria-pressed or aria-selected; no live announcement for empty search or camera denial; scrollable-region-focusable in 4/4 export states.",
  "SC 4.1.2, 1.3.1, 4.1.3, 2.1.1.", "evidence/W2-browser/scripts/05-keyboard-a11y.mjs", ["agents/W2-browser-a11y-ux.md MSR-A11Y-007/008/010"],
  "Assistive-technology users miss state and results.", "Several widgets.", "Add ARIA states, a role=status region, and tabindex=0 on the pre.", "axe and the scripted checks pass.", "0.5 day.", ["W2"]),
F("MSR-UX-001", "The studio claims 'full WCAG 2.2 compliance' for every color pairing and labels contrast ratios 'WCAG AA/AAA'",
  "Accessibility content / A07+A08", "Medium", "high", "source-confirmed", ["app/app.js:2527", "app/app.js:1898-1908"],
  "'این ترکیب با رعایت کامل استانداردهای WCAG 2.2 و کنتراست سطوح کالیبره شده است' is appended to every mockup.",
  "A contrast ratio speaks only to SC 1.4.3/1.4.6; conformance is a page-level claim. Combined with MSR-A11Y-001 the claim is false in light theme.",
  "Read source; see screenshot.", ["evidence/W2-browser/screens/light-drawer-heading.jpg"], "Misleads designers about accessibility.", "Every mockup and badge.",
  "Say 'contrast ratio 7.1:1 (meets the SC 1.4.6 threshold for normal text)' instead.", "No UI string claims WCAG compliance.", "1 hour.", ["W2", "A00"]),
F("MSR-UX-002", "The AR dialog claims 'photometric matching', but the Kelvin buttons only recolor an outline", "UX content / A07", "Low", "high", "reproduced",
  ["app/template.html:1640", "app/app.js:1019-1028"], "The 3000K/5500K buttons change a border tint only.", "Describe the simulation accurately.",
  "evidence/W2-browser/results/02-workflows.json ar-kelvin-cycle", ["evidence/W2-browser/screens/wf-ar-camera-fake.jpg"], "Overclaim.", "AR dialog.",
  "Rename it to 'color preview on the camera image (not photometric)'.", "The wording is changed.", "30 minutes.", ["W2"]),
F("MSR-UX-003", "Mislabelled technical panels and minor UX defects (version badge V2.0 vs v3.0.0, blank icons, same filename for two exports)", "UX / A07", "Low", "high", "reproduced",
  ["app/template.html:384", "app/app.js:3365-3394"], "See W2 MSR-UX-006/008.", "Consistent labels.", "W2 scripts 02.", ["agents/W2-browser-a11y-ux.md"], "Confusion.", "Several.", "Fix labels and filenames.", "The W2 list is cleared.", "2-4 hours.", ["W2"]),
F("MSR-DATA-002", "Data-quality report hard-codes unverifiedHeritageColors and measuredSpectra; the formula-conflict check can never fire", "Data / A04+A13", "Medium", "high", "source-confirmed",
  ["packages/core/src/tokens/palettes.ts:72", "packages/core/scripts/core.test.js:97"], "'unverifiedHeritageColors: colors.length, measuredSpectra: 0'.",
  "Counts must be derived from per-record status so that progress (or regression) is visible.", "evidence/A13-qa/diagnostic.test.mjs", ["DATA_QUALITY.md §1"],
  "The report can never show a verified record; the test asserting the counts is tautological.", "Report, test and docs.", "Derive the counts from provenance fields; add separate documentary, measurement and design status fields.",
  "The diagnostic DEFECT test passes; changing one record's status changes the report.", "2-4 hours.", ["A00", "W1", "A13"]),
F("MSR-DATA-003", "Most exports drop the provenance caveats (Tailwind, Swift, Kotlin, Tokens Studio, and in-studio CSS/SCSS/Flutter) and carry 'اصیل' into names",
  "Data / A04+A10", "Medium", "high", "reproduced", ["packages/core/tokens/tailwind-theme.css, Colors.swift, ColorSchemes.kt, tokens-studio.json", "app/app.js:3365-3394, 819-826"],
  "Zero caveat strings in those outputs; JSON and DTCG in-studio downloads share the filename persian-palettes.json.",
  "Exporters preserve caveats or document where the format cannot (audit brief §4D).", "grep outputs; W2 downloads.", ["DATA_QUALITY.md §5", "evidence/W2-browser/downloads/"],
  "An 'unverified' source turns into an 'authentic' export.", "6 formats.", "Add a header caveat comment to each text format; strip the adjective from names.", "Each export contains the caveat line.", "2-4 hours.", ["W1", "W2"]),
F("MSR-DATA-004", "Dataset is hard to cite: no CITATION.cff, no data/annotation license, no version/date in data-quality.json, position-based IDs",
  "Data / A04", "Low", "high", "source-confirmed", ["repository root", "LICENSE", "packages/core/tokens/data-quality.json"], "No citation metadata.",
  "Citable releases with version, license and correction history.", "ls; read files.", ["DATA_QUALITY.md §6"], "Cannot be cited reliably.", "Repository.",
  "Add CITATION.cff (no invented DOI), a data license statement, a version and date in the report, and a CHANGELOG of corrections.", "The files exist and are valid (cffconvert --validate).", "2 hours.", ["W1"]),
F("MSR-API-001", "Token paths and platform identifiers derive from English display names and array positions, not stable IDs", "API / A01+A10", "Medium", "high", "reproduced",
  ["packages/core/src/exporters/w3c.ts:7-8", "packages/core/src/exporters/tailwind.ts:15,37", "packages/core/src/exporters/platforms.ts:9-11", "app/app.js:3375-3378"],
  "Renaming 'Ultramarine Lapis' changes the DTCG path; reordering a palette changes Tailwind/Swift names; five naming schemes coexist across exports.",
  "Consumer-facing identifiers are stable across corrections.", "evidence/A13-qa/diagnostic.test.mjs (token-path test)", ["agents/W3-security-licenses-interop-release.md MSR-INT-002"],
  "Data corrections silently break consumers; the brand migration must preserve names.", "All exports.", "Key tokens by stable ID with the name as an alias; document the positional slots.", "The diagnostic token-path test passes.", "0.5-1 day (major-version change).", ["A00", "W3"]),
F("MSR-INT-002", "Tailwind steps 100-600 are ordinal positions, not a lightness scale (non-monotonic in 12/12 palettes)", "Interop / A10", "Low", "high", "reproduced",
  ["packages/core/src/exporters/tailwind.ts:13-15, 32-33"], "e.g. isfahan-tiles Oklab L: 0.31, 0.79, 0.65, 0.77, 0.96, 0.19.", "Tailwind convention: higher step = darker. The docs say the slots are curated, but class names imply a scale.",
  "evidence/W3-security/interop/tailwind-step-lightness.log", ["evidence/W3-security/interop/"], "Designers pick wrong shades.", "12 palettes.",
  "Use semantic slot names (e.g. -c1) or sort by lightness in a new major version.", "The naming decision is documented and tested.", "2 hours.", ["W3"]),
F("MSR-INT-001", "Exporters emit injectable or invalid output for caller-supplied palettes (CSS comment break-out, raw hex, invalid Swift/Kotlin identifiers, DTCG-reserved names)", "Interop/Security / A10+A11", "Low", "high", "reproduced",
  ["packages/core/src/exporters/tailwind.ts:30-35", "platforms.ts:5-7,15-16", "w3c.ts:22", "figma.ts:10"],
  "See agents/W3-SENSITIVE.md S1; the Kotlin id '1st-palette' fails to compile.", "Validate identifiers and escape comments at the exporter boundary.",
  "evidence/W3-security/exporter-injection-probe.mjs", ["evidence/W3-security/exporter-injection-probe.log", "evidence/W3-security/kotlin-compile.log"],
  "Only affects consumers who pass untrusted palettes (Medium if they do).", "5 exporters.", "Add input validation with clear errors.", "The probe cases throw or are escaped.", "0.5 day.", ["W3", "A13"]),
F("MSR-INT-003", "Compose ColorScheme export covers 24 of 36 Material 3 roles", "Interop / A10", "Low", "high", "reproduced", ["packages/core/src/math/hct.ts:6-12"],
  "inverse*, scrim, surfaceTint and surfaceContainer* fall back to Material baseline colors.", "Emit all roles that MCU's DynamicScheme provides.", "javap on material3 1.7.3",
  ["evidence/W3-security/kotlin-compile.log"], "Mixed Persian/baseline colors in apps.", "All 12 schemes.", "Add the remaining roles.", "kotlinc compiles; all 36 parameters are set.", "2 hours.", ["W3"]),
F("MSR-INT-004", "Figma importer is not a runnable plugin and is not idempotent", "Interop / A10", "Low", "medium (static only)", "source-confirmed", ["docs/figma-import.js:1-15"],
  "No manifest, the function is never invoked, and each run creates a new collection.", "A usable importer, or accurate documentation.", "tsc --checkJs with plugin typings", ["evidence/W3-security/figma-typecheck.log"],
  "Users must build their own plugin.", "Figma users.", "Ship a minimal plugin with a manifest; update existing collections by name.", "Import twice into a Figma file -> one collection.", "0.5-1 day.", ["W3"]),
F("MSR-REL-001", "The v3.0.0 release was built outside CI from a pre-correction commit and still distributes retracted claims; assets are mutable CRLF builds",
  "Release / A14", "Medium", "high", "reproduced", ["GitHub release v3.0.0 (tag -> 2e06892)", "release/manshour-studio-3.0.0.zip README.md lines 4, 40, 46"],
  "The ZIP README says 'Enterprise-Grade', '72 authentic colors', '72 authenticated pigment formulas', '100% offline'. The release body was corrected but the assets were not.",
  "Distributed artifacts must not contradict current claims; releases should come from tested commits.", "Compare the ZIP entries with git show HEAD:<path>; GitHub release API.",
  ["evidence/W3-security/release-ci-facts.log", "agents/A00-lead-sequential-passes.md A00"], "Downloaders get the retracted claims.", "The v3.0.0 ZIP and HTML assets.",
  "Do not replace the historical assets. Add a prominent release note and a v3.0.1 release built in CI from a corrected commit; consider marking v3.0.0 as superseded.",
  "A new release's assets are built by CI from its tag; the ZIP README matches the tagged README.", "0.5 day.", ["W3", "A00"],
  artifact="GitHub release v3.0.0 assets"),
F("MSR-REL-002", "Generated files are not checked for freshness; the committed build manifest describes CRLF bytes, so pack:studio fails on a clean checkout; no .gitattributes; float drift across platforms",
  "Build / A14", "Medium", "high", "reproduced", ["docs/build-manifest.json", ".github/workflows/ci.yml (no git diff --exit-code)", "scripts/package-release.py:10-11", "packages/core/tokens/w3c-tokens.json"],
  "The rebuild rewrites the manifest and 138 float lines; pack:studio exits 1 on a clean checkout.", "A clean checkout builds and packages; CI rejects stale generated files.",
  "npm ci && python3 scripts/package-release.py (exit 1); npm run check && git status.", ["evidence/A00-baseline/pack-studio-committed-manifest.log.txt", "evidence/A13-qa/diagnostic.test.mjs"],
  "Contributors hit failures; hashes cannot be trusted.", "Repository and CI.", "Add .gitattributes (eol=lf), round token floats, run git diff --exit-code and pack:studio in CI.",
  "CI fails when generated files are stale; pack:studio passes on a clean checkout.", "2-4 hours.", ["A00", "W3"]),
F("MSR-REL-003", "CommonJS TypeScript consumers cannot import exported types (index.d.cts uses export =)", "Package / A01+A14", "Low", "high", "reproduced",
  ["packages/core/scripts/build.js:19 -> dist/index.d.cts"], "TS2305 'has no exported member PersianPaletteDefinition'.", "Types are importable from .cts.",
  "evidence/W3-security/cts-type-import.log", ["evidence/W3-security/cts-type-import.log"], "CJS TS users lose types.", "CJS TypeScript users.",
  "Generate real .d.cts declarations (e.g. tsup/dts) or re-export the types.", "A .cts type import compiles.", "2 hours.", ["W3"]),
F("MSR-REL-004", "Package payload and metadata hygiene (duplicate 400 KB token file, unused types forwarder, no sideEffects or ./package.json export)", "Package / A14", "Low", "high", "source-confirmed",
  ["packages/core/package.json", "packages/core/tokens/style-dictionary.json", "packages/core/types/index.d.ts"], "style-dictionary.json is byte-identical to w3c-tokens.json.", "A lean, well-described package.",
  "Read the files.", ["agents/W3-security-licenses-interop-release.md §7"], "Larger install; weaker tooling support.", "Package.", "Remove the duplicate (or alias it via exports), add sideEffects:false and the ./package.json export.", "The package lint passes.", "1 hour.", ["W3", "A00"]),
F("MSR-REL-005", "Inactive release template would publish with write permission, unpinned actions and hard-coded version", "CI / A14", "Low", "high", "source-confirmed",
  [".github/workflows-templates/release.yml:12-48"], "contents: write; @v4/@v5/@v2 tags; hard-coded 3.0.0.", "Pinned actions, version from the tag.", "Read the file.",
  ["agents/W3-security-licenses-interop-release.md §7"], "Risk if activated as is.", "Template only.", "Pin SHAs and derive file names from the tag before activating.", "actionlint passes; no hard-coded version.", "1 hour.", ["W3"]),
F("MSR-REL-006", "npm start does not serve the English edition documented beside it", "Build / A14", "Low", "high", "reproduced", ["scripts/serve.mjs:11-12"],
  "GET /code_artifact_en.html -> 404.", "The documented editions are served.", "curl http://127.0.0.1:4173/code_artifact_en.html", ["evidence/W3-security/serve-probe.log"],
  "English users cannot use npm start for their edition.", "Local server.", "Add the route.", "The route returns 200.", "15 minutes.", ["W3", "W2"]),
F("MSR-SEC-001", "No CSP is possible for the studio HTML (114 inline handlers, 26 innerHTML templates); the local server lacks a Host check and follows symlinks", "Security / A11", "Low", "high", "source-confirmed",
  ["app/app.js (sink table in W3 §3)", "scripts/serve.mjs:12-18"], "No sink is reachable from untrusted input today; the pattern blocks a strict CSP.", "Defense in depth.",
  "Grep for sinks; live server probes (W3-SENSITIVE.md S2).", ["evidence/W3-security/dom-sinks.log", "evidence/W3-security/serve-probe.log"],
  "Latent risk if user imports are added.", "Studio and dev server.", "Move to addEventListener/textContent, add a CSP meta, and add realpath and a Host allow-list in serve.mjs.", "A CSP without unsafe-inline loads without violations.", "1-2 days.", ["W3"]),
F("MSR-SEC-002", "Archived v2.1.0 HTML (in the repo and the release ZIP) runs unversioned CDN scripts without SRI", "Security / A11", "Low", "high", "source-confirmed",
  ["archive/v2.1.0/code_artifact.html"], "Loads cdn.tailwindcss.com and cdnjs three r128 with no integrity attribute.", "Archived artifacts should not execute mutable remote code.", "grep script src.",
  ["agents/W3-security-licenses-interop-release.md MSR-SEC-002"], "Supply-chain risk for anyone opening the archive.", "Archive.", "Add a warning or strip the scripts from the archived copy.", "No remote script without SRI.", "30 minutes.", ["W3"]),
F("MSR-SEC-003", "The npm package name and brand scope are unregistered; a third party could publish under the documented name", "Security/Release / A14", "Low", "medium: package 404 verified; scope ownership not checked", "suspected",
  ["README.md, QUICKSTART.md (package name)", "BRAND_MIGRATION.md §4"], "npm view @persian-palette/core -> 404 on 2026-09-25; @manschourey/core -> 404.",
  "Claim the scope before publicizing npm installation.", "npm view <name>", ["BRAND_MIGRATION.md"], "Name-squatting or confusion if users run npm install by name.", "Future users.",
  "Register the chosen scope; keep the tarball instructions until then.", "npm org exists and is owned by the maintainer.", "30 minutes.", ["A00"]),
F("MSR-LIC-002", "APCA-W3 use restrictions (web-content only, commercial agreement, terminology) are not surfaced to consumers", "Licensing / A12", "Medium", "medium: terms clear, applicability is legal", "source-confirmed",
  ["docs/licenses/apca-w3.md", "THIRD_PARTY_NOTICES.md", "app/app.js:388 ('SAPC-0.0.98G Implementation')"], "The restrictions appear only in the license file.", "Consumers learn the restrictions before adopting.",
  "Read the license and README.", ["SECURITY_AND_LICENSES.md §3"], "Unintended non-compliant downstream use.", "npm and token consumers.", "Add an 'APCA-W3 terms' section; fix the version label; ask counsel.", "The README contains the restrictions.", "2-4 hours plus counsel.", ["W3"]),
F("MSR-LIC-003", "Standalone HTML assets lack full third-party license texts; hotlinked Wikimedia photos have no attribution and unknown licenses", "Licensing / A12", "Medium", "medium: facts high, sufficiency legal; Commons blocked", "evidence-gap",
  ["code_artifact.html, code_artifact_en.html", "heritage-data.ts imageUrl (12)", "app/app.js:2076-2085"], "Headers only; no per-image credit.", "Notices accompany each distribution; CC BY/BY-SA credit.",
  "Inspect the HTML; W2 photo-mode run.", ["SECURITY_AND_LICENSES.md §3", "evidence/W2-browser/screens/wf-photo-mode-offline.jpg"], "Possible license non-compliance.", "HTML assets; 12 images.",
  "Add a licenses page to the HTML; record per-image credits or disable photo mode.", "Each image shows author, license and link; the HTML includes the full texts.", "0.5-1 day plus counsel.", ["W3", "W2"]),
F("MSR-GOV-001", "Package author 'Persian Palette Vault Working Group' and copyright holder 'contributors' imply a group; the sole maintainer is not named; AI-assistance disclosure omits tools evidenced in the repo",
  "Governance / A06", "Medium", "high", "source-confirmed", ["packages/core/package.json:5", "LICENSE:3", "packages/core/LICENSE:3", "SECURITY.md:12", "docs/ROADMAP.md:16", "review-2026-09-21.md:5,13-16"],
  "No file names Majid ZeidAbadiNejad; ROADMAP mentions only Codex while review-2026-09-21.md records an Antigravity session.", "Truthful attribution; no fictitious teams (audit brief §1, §4J).",
  "Read the files.", ["EDITORIAL_REWRITE_SAMPLES.md §5"], "Misrepresents project governance to funders and users.", "Package metadata, license and docs.",
  "Set author to the maintainer; add an About section with an accurate AI-assistance disclosure; the owner decides the copyright line with counsel.", "No 'Working Group' string remains; the About section exists.", "1 hour.", ["A00", "W3"]),
F("MSR-DOC-001", "Repository-root notes contradict current verification scope and expose local paths (walkthrough claims final live-browser approval; file:/// links; AI session paths)",
  "Docs / A06", "Medium", "high: verbatim", "source-confirmed", ["walkthrough.md:3, 9-10, 38, 45", "implementation_plan.md:21", "docs/verification.md:30", "review-2026-09-21.md:5, 13-16, 22"],
  "'تست زنده رابط کاربری با DevTools مرورگر به تایید نهایی رسیده است' vs 'A live local-app browser session was not performed'.", "Current claims are unambiguous; historical notes are labeled as such.",
  "Read the files.", ["agents/A00-lead-sequential-passes.md A06"], "Readers get contradictory verification claims.", "3 root documents.",
  "Move walkthrough/implementation_plan/review into docs/history/ with a 'historical, superseded' banner; redact local paths.", "No root document claims unperformed verification; grep for 'file:///c:' returns 0.", "1 hour.", ["A00", "W1"]),
F("MSR-API-002", "evaluateAPCA().minFontSizePx reports apca-w3 special codes (999/777) as pixel sizes", "API / A01", "Low", "high", "reproduced", ["packages/core/src/math/apca.ts:20,31"],
  "evaluateAPCA('#777777','#808080').minFontSizePx.fontNormal400 = 999.", "Return null or a flag for 'not usable'.", "evidence/A13-qa/diagnostic.test.mjs", ["evidence/A02-color/oracle-comparison.out.json"],
  "Consumers may render 999px guidance.", "API.", "Map codes >= 400 to null plus a reason.", "The diagnostic test passes.", "1 hour.", ["A00"]),
F("MSR-API-003", "hctToHex silently reduces unreachable chroma without reporting the achieved value", "API / A01", "Low", "high", "reproduced", ["packages/core/src/math/hct.ts:32-36"],
  "Requested chroma 150 -> achieved 52.3.", "Document it or return the achieved HCT.", "oracle-comparison hctInverse", ["evidence/A02-color/oracle-comparison.out.json"], "Surprising results.", "API.", "Document; add hctToColor returning the achieved HCT.", "The docs state the behavior.", "1 hour.", ["A00"]),
F("MSR-API-004", "Studio UI silently substitutes #120A8F for invalid color input and keeps dead duplicate math with a misleading 'SAPC-0.0.98G Implementation' comment", "API/UI / A01", "Low", "high", "source-confirmed",
  ["app/app.js:1857-1864", "app/app.js:787-795, 1730-1739", "app/app.js:388-391"], "hexToRgb returns ultramarine on error.", "No silent substitution (the migration guide's own contract).", "Read source.",
  ["agents/A00-lead-sequential-passes.md A01"], "Hides errors; maintenance cost.", "Studio.", "Throw or show an error; delete the dead helpers; fix the comment.", "Invalid input shows an error.", "1 hour.", ["A00"]),
F("MSR-QA-001", "The test suite includes tautological/static checks, no browser E2E, unasserted doc-example values, and no generated-file freshness check", "QA / A13", "Medium", "high", "source-confirmed",
  ["packages/core/scripts/core.test.js:97", "tests/integration.test.mjs (test 7 static string checks)", "scripts/verify-package.mjs (exit-code-only examples)"],
  "The measuredSpectra===0 assertion cannot fail; 'accessibility affordances' is a grep test.", "Tests with independent oracles and failure modes that can actually fail.", "Read the tests; run diagnostic.test.mjs.",
  ["evidence/A13-qa/proposed-tests.md"], "Green CI overstates quality; the defects in this report passed CI.", "Test suite.", "Adopt proposed-tests.md items 1-7.", "Each proposed test exists and fails on the baseline defect it targets.", "2-4 days.", ["A00"]),
F("MSR-GFX-001", "WebGL scene renders about 60 fps from page load while the 3D drawer is hidden", "Performance / A09", "Medium", "high: renderer.info frame count; real-GPU cost not measured", "reproduced",
  ["app/app.js:1662", "app/app.js:3469-3481", "app/app.js:2999-3005 (radar loop)"], "181 frames in 3 s with the drawer closed; about 10 fps under reduced motion.", "Render only while visible.",
  "evidence/W2-browser/scripts/06-perf-graphics.mjs", ["evidence/W2-browser/results/06-perf-graphics.json"], "Battery and CPU drain on every visit.", "All sessions.",
  "Initialize lazily; start and stop the rAF loop with the drawer.", "The frame counter does not advance while hidden.", "2-4 hours.", ["W2"]),
F("MSR-GFX-002", "No fallback for missing WebGL, no context-loss handling, no canvas resize", "Graphics / A09", "Low", "high", "reproduced", ["app/app.js:1662", "app/app.js:3397-3482", "app/app.js:3577-3587"],
  "With WebGL disabled the drawer shows an empty canvas and 'WebGL Three.js GPU'.", "A graceful text fallback.", "evidence/W2-browser/scripts/06, 09", ["evidence/W2-browser/screens/webgl-unavailable-drawer.jpg"],
  "A broken-looking feature.", "Users without WebGL.", "Show a fallback; handle webglcontextlost; add a ResizeObserver.", "A no-WebGL run shows the fallback text.", "2-4 hours.", ["W2"]),
F("MSR-GFX-003", "3.14 MB per HTML edition, with 1.66 MB of base64 fonts (lab FCP about 350 ms, load about 680 ms from file://)", "Performance / A09", "Low", "high for bytes; medium for timings (headless lab)", "reproduced",
  ["scripts/build-app.mjs:33-39"], "The EN edition duplicates everything; the full Font Awesome sets are embedded.", "Subset the fonts and icons.", "evidence/W2-browser/scripts/06", ["evidence/W2-browser/results/06-perf-graphics.json"],
  "Slow on constrained networks.", "Both editions.", "Subset the icons and Vazirmatn weights; lazy-load three.js.", "Size below 1.5 MB per edition.", "1 day.", ["W2"]),
F("MSR-CULT-006", "'Persian dastgah' sound effects use Western 12-tone equal-tempered pitches", "Cultural / A03", "Low", "medium: frequencies exact; microtonal requirement is background knowledge", "source-confirmed",
  ["app/app.js:1667, 1675, 1700"], "The toast says 'افکت‌های هارمونیک دستگاه‌های موسیقی ایرانی فعال شدند' but the frequencies are 12-TET.", "Do not name a tradition the implementation does not follow.",
  "evidence/W1-cultural/dastgah-12tet-check.out.txt", ["evidence/W1-cultural/dastgah-12tet-check.out.txt"], "Misrepresents Persian music.", "Sound effects.", "Rename the effect, or implement dastgah intervals with a specialist.", "The UI wording changes.", "30 minutes (rename).", ["W1"]),
]

if __name__ == "__main__":
    doc = {
        "schema": "manschourey-audit-findings/1",
        "baseline_commit": BASE,
        "generated": "2026-09-25",
        "severity_scale": ["Critical", "High", "Medium", "Low"],
        "status_values": ["reproduced", "source-confirmed", "suspected", "evidence-gap"],
        "count": len(FINDINGS),
        "findings": FINDINGS,
    }
    print(json.dumps(doc, ensure_ascii=False, indent=2))
